# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - bundle install --without=documentation
  - bundle exec pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/$POD_NAME.xcworkspace -scheme $POD_NAME-Example -sdk iphonesimulator$OS_VERSION -destination 'platform=iOS Simulator,OS=$OS_VERSION,name=iPhone $PHONE_VERSION' ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  - bundle exec pod lib lint
after_success: bundle exec slather